---
title: "Longyu Zhang"
author: "(+1)551-234-1358 lz2951@cumc.columbia.edu"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

# Education

- School of Life Sciences and Biotechnology, Shanghai Jiao Tong University <p align="right">Sept 2018 - Aug 2022</p>
B.S. in Bioinformatics

- Mailman School of Public Health, Columbia University Irving Medical Center <p align="right">Sept 2023 - Now</p>
M.S. in Biostatistics

# Research Experience

## The Exploration of Multi-omics Data Analysis Algorithm Based on Persistent Homology
Shanghai Jiao Tong University | Undergraduate Research Assistant <p align="right">Sept 2021 - Aug 2022</p>

- Applied persistent homology method to multi-omics data obtained from TCGA including RNA-seq, DNA methylation and phenotype data

- Linked zero-dimensional topological characteristics of omics data point clouds to clustering characteristics of samples and also linked the one-dimensional topological characteristics with the sample interaction

- Proved that case group samples with lung adenocarcinoma have stronger heterogeneity compared to control group using topological invariant sum death time (SDT) of zero-dimensional topological structure

- Divided lung adenocarcinoma samples and glioblastoma multiforme samples into two subtypes according to result of persistent homology analysis, which is consistent with general classification method of these two kinds of cancer

- Discovered persistent homology method is appropriate for high-dimensional data without dimension reduction but computationally demanding

## The prospective study of the impact of antioxidant nutrients intake on the levels of immunological indicator and the expression of related genes
Shanghai Jiao Tong University | Undergraduate Research Assistant <p align="right">Oct 2020 - Oct 2021</p>

- Reviewed existing literature on relationship between antioxidant nutrients and immune system, deciding to focus research on relationship between asthma and selenium

- Collected data from National Health and Nutrition Examination Survey (NHANES) and designed data analysis pipeline according to demographic characteristics and weights of samples 

- Wrote R and Python scripts to eliminate invalid data and conduct analysis using logistic regression model

- Proved that blood selenium, as well as family income and gender, is significantly related to asthma for NHANES participants of all ages

## Controllable construction of zein/caseinate/pectin composite particles and its application in food nutrient delivery systems 
Shanghai Jiao Tong University | Undergraduate Research Assistant <p align="right">Apr 2019 - Apr 2020</p>

- Operated centrifugal machine and lyophilizer to prepare lyophilized zein-caseinate-pectin composite particles

- Constructed zein-caseinate-pectin composite particles using anti-solvent method and characterized their stronger stability and re-dispersibility compared to zein-caseinate composite particles by measuring particle size, particle polydispersity index (PDI) and $\zeta$-potential of particles at different acidic pH values

- Constructed curcumin-loaded zein-caseinate-pectin particles and proved satisfactory in-vitro release behavior and stability of these particles using curcumin as a probe compound

- Demonstrated that zein-caseinate-pectin composite particles have potential as a delivery system for nutrients in foods and drinks

# Project

## Diagnosis of pulmonary nodule malignancy using machine learning 
Course project: Biological Big Data Analysis <p align="right">Spring semester 2020-2021</p>

- Collaborated with 3 groupmates to create supervised machine learning model to diagnose pulmonary nodule malignancy in mhd form lung CT image files with malignancy label 

- Utilized Python to preprocess original data, write scripts to get one-hot code recognizing malignancy, and transform original mhd data into npy 

## Ylands Sandbox Game Design 
Project supported by Tencent Institute of Games <p align="right">Fall semester 2019-2020</p>

- Applied game development theory to game design tools with 3 groupmates to create video game, with resulting demo highly ranked by Tencent professionals in final presentation

- Designed demo maze and distributed game resources  

## Programming to find differences between two files containing bioinformatics data 
Course project: Programming Languages for Bioinformatics <p align="right">Spring semester 2019-2020</p>

- Worked independently to finish program comparing content of two different files line by line in one of two specific ways, and output comparison results into result files of up to 4,700,000 lines

- Wrote C program with 500+ lines of code to finish comparison between files with 4,700,000 and 300,000 lines in less than 4s, one of the fastest programs in the class 
